services:
  docker-api:
    build: ./src
    restart: always
    container_name: docker-api
    command: bash -c "export PYTHONPATH="${PYTHONPATH}:/usr/src/app/" && echo $PYTHONPATH && cd ./database && alembic upgrade heads"
    entrypoint: python ./app.py
    ports:
      - "8000:80"
    volumes:
      - ./entry.sh:/usr/src/app/entry.sh
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: mariadb
    container_name: database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
